package org.uniko.camundaSimulator.engine.context;

public enum ContextApplicationTarget {

    // Worker values
    NAME,
    PERFORMANCE,

    // Process values
    INTERVAL,

    // Task values
    PROCESSING_TIME,

    // Process variable values
    LOWER_BOUND,
    UPPER_BOUND,
    MEAN,
    STANDARD_DEVIATION,
    DECIMAL_PLACES,
    CHANCE,

    // Schedule values
    DEFAULT_START_TIME,
    MONDAY_START_TIME,
    TUESDAY_START_TIME,
    WEDNESDAY_START_TIME,
    THURSDAY_START_TIME,
    FRIDAY_START_TIME,
    SATURDAY_START_TIME,
    SUNDAY_START_TIME,

    DEFAULT_ACTIVE_HOURS,
    MONDAY_ACTIVE_HOURS,
    TUESDAY_ACTIVE_HOURS,
    WEDNESDAY_ACTIVE_HOURS,
    THURSDAY_ACTIVE_HOURS,
    FRIDAY_ACTIVE_HOURS,
    SATURDAY_ACTIVE_HOURS,
    SUNDAY_ACTIVE_HOURS,

    DEFAULT_INACTIVE_DAYS,
    JANUARY_INACTIVE_DAYS,
    FEBRUARY_INACTIVE_DAYS,
    MARCH_INACTIVE_DAYS,
    APRIL_INACTIVE_DAYS,
    MAY_INACTIVE_DAYS,
    JUNE_INACTIVE_DAYS,
    JULY_INACTIVE_DAYS,
    AUGUST_INACTIVE_DAYS,
    SEPTEMBER_INACTIVE_DAYS,
    OCTOBER_INACTIVE_DAYS,
    NOVEMBER_INACTIVE_DAYS,
    DECEMBER_INACTIVE_DAYS
}
