# Spring application configuration
spring:
  main:
    web-application-type: none

  shell:
    interactive:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:workflowsimulationdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

# Camunda instance default configuration
camunda:
  operate:
    address: http://localhost:8081

  tasklist:
    address: http://localhost:8082
    process:
      name: "Demo Process - Tutorial 2"

  elasticsearch:
    address: localhost:9200

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true

# Keycloak instance default configuration
keycloak:
  address: http://localhost:18080
  credentials:
